[workspace]

members = [
    "kimojio",
    "kimojio-macros",
    "kimojio-tls",
    "kimojio-util",
    "kimojio-tests",
    "perf",
    "examples/copyfile",
    "examples/tls-echo-server",
]

resolver = "3"

[workspace.package]
version = "0.14.0"
edition = "2024"
license = "MIT"
homepage = "https://github.com/Azure/kimojio-rs"
repository = "https://github.com/Azure/kimojio-rs"
readme = "README.md"

[workspace.dependencies]
cc = "1"
criterion = { version = "0.7", default-features = false }
foreign-types-shared = "0.1"
futures = "0.3"
impls = "1"
intrusive-collections = "0.9"
kimojio = { path = "kimojio", version = "0.14.0" }
kimojio-macros = { path = "kimojio-macros", version = "0.14.0" }
kimojio-tls = { path = "kimojio-tls", version = "0.14.0" }
libc = "0.2"
openssl = "0.10"
pin-project-lite = "0.2"
rcgen = { version = "0.14", features = ["x509-parser"] }
roaring = "0.11"
rustix = { version = "1", features = [
    "io_uring",
    "mount",
    "fs",
    "mm",
    "process",
    "rand",
    "system",
    "time",
    "thread",
] }
rustix-uring = { version = "0.6" }
scopeguard = "1"
static_assertions = "1"
tempfile = "3"
uuid = { version = "1", features = ["v4"] }
zerocopy = { version = "0.8", features = ["derive"] }

# from macros
quote = "1"
syn = { version = "2", features = ["full"] }

# for examples
anyhow = "1"
clap = { version = "4", features = ["derive"] }

# for kimojio-util
futures-util = { version = "0.3", default-features = false, features = ["io", "std"] }
kimojio-util = { path = "kimojio-util", version = "0.14.0" }

# for testing (kimojio-tests)
bytes = "1"
http-body-util = "0.1"
hyper = { version = "1", default-features = false, features = ["http1", "server", "client"] }
hyper-util = { version = "0.1", default-features = false, features = ["tokio", "http1", "client"] }
tokio = { version = "1", default-features = false, features = ["io-util"] }
tokio-util = { version = "0.7", default-features = false, features = ["compat"] }
